# Generated by teaql-code-gen
from requests.commerce_platform_request import CommercePlatformRequest
from requests.customer_request import CustomerRequest
from requests.order_status_request import OrderStatusRequest
from requests.customer_order_request import CustomerOrderRequest
from requests.product_request import ProductRequest
from requests.order_line_request import OrderLineRequest
from requests.order_search_preset_request import OrderSearchPresetRequest

class Q:
    @staticmethod
    def commerce_platforms() -> CommercePlatformRequest:
        return CommercePlatformRequest(minimal=False)

    @staticmethod
    def commerce_platforms_minimal() -> CommercePlatformRequest:
        return CommercePlatformRequest(minimal=True)

    @staticmethod
    def customers() -> CustomerRequest:
        return CustomerRequest(minimal=False)

    @staticmethod
    def customers_minimal() -> CustomerRequest:
        return CustomerRequest(minimal=True)

    @staticmethod
    def order_statuses() -> OrderStatusRequest:
        return OrderStatusRequest(minimal=False)

    @staticmethod
    def order_statuses_minimal() -> OrderStatusRequest:
        return OrderStatusRequest(minimal=True)

    @staticmethod
    def customer_orders() -> CustomerOrderRequest:
        return CustomerOrderRequest(minimal=False)

    @staticmethod
    def customer_orders_minimal() -> CustomerOrderRequest:
        return CustomerOrderRequest(minimal=True)

    @staticmethod
    def products() -> ProductRequest:
        return ProductRequest(minimal=False)

    @staticmethod
    def products_minimal() -> ProductRequest:
        return ProductRequest(minimal=True)

    @staticmethod
    def order_lines() -> OrderLineRequest:
        return OrderLineRequest(minimal=False)

    @staticmethod
    def order_lines_minimal() -> OrderLineRequest:
        return OrderLineRequest(minimal=True)

    @staticmethod
    def order_search_presets() -> OrderSearchPresetRequest:
        return OrderSearchPresetRequest(minimal=False)

    @staticmethod
    def order_search_presets_minimal() -> OrderSearchPresetRequest:
        return OrderSearchPresetRequest(minimal=True)

