# Generated by teaql-code-gen
from requests.commerce_platform_request import CommercePlatformRequest
from requests.customer_request import CustomerRequest
from requests.order_status_request import OrderStatusRequest
from requests.customer_order_request import CustomerOrderRequest
from requests.product_request import ProductRequest
from requests.order_line_request import OrderLineRequest
from requests.order_search_preset_request import OrderSearchPresetRequest

class Q:
    @staticmethod
    def commerce_platforms() -> CommercePlatformRequest:
        return CommercePlatformRequest()

    @staticmethod
    def customers() -> CustomerRequest:
        return CustomerRequest()

    @staticmethod
    def order_statuses() -> OrderStatusRequest:
        return OrderStatusRequest()

    @staticmethod
    def customer_orders() -> CustomerOrderRequest:
        return CustomerOrderRequest()

    @staticmethod
    def products() -> ProductRequest:
        return ProductRequest()

    @staticmethod
    def order_lines() -> OrderLineRequest:
        return OrderLineRequest()

    @staticmethod
    def order_search_presets() -> OrderSearchPresetRequest:
        return OrderSearchPresetRequest()

