# Generated by teaql-code-gen
from requests.platform_request import PlatformRequest
from requests.school_type_request import SchoolTypeRequest
from requests.school_request import SchoolRequest

class Q:
    @staticmethod
    def platforms() -> PlatformRequest:
        return PlatformRequest(minimal=False)

    @staticmethod
    def platforms_minimal() -> PlatformRequest:
        return PlatformRequest(minimal=True)

    @staticmethod
    def school_types() -> SchoolTypeRequest:
        return SchoolTypeRequest(minimal=False)

    @staticmethod
    def school_types_minimal() -> SchoolTypeRequest:
        return SchoolTypeRequest(minimal=True)

    @staticmethod
    def schools() -> SchoolRequest:
        return SchoolRequest(minimal=False)

    @staticmethod
    def schools_minimal() -> SchoolRequest:
        return SchoolRequest(minimal=True)

