# Generated by teaql-code-gen
from requests.platform_request import PlatformRequest
from requests.work_item_request import WorkItemRequest

class Q:
    @staticmethod
    def platforms() -> PlatformRequest:
        return PlatformRequest(minimal=False)

    @staticmethod
    def platforms_minimal() -> PlatformRequest:
        return PlatformRequest(minimal=True)

    @staticmethod
    def work_items() -> WorkItemRequest:
        return WorkItemRequest(minimal=False)

    @staticmethod
    def work_items_minimal() -> WorkItemRequest:
        return WorkItemRequest(minimal=True)

