# Generated by teaql-code-gen
from requests.platform_request import PlatformRequest
from requests.customer_order_request import CustomerOrderRequest
from requests.order_item_request import OrderItemRequest
from requests.payment_request import PaymentRequest
from requests.payment_attempt_request import PaymentAttemptRequest
from requests.shipment_request import ShipmentRequest

class Q:
    @staticmethod
    def platforms() -> PlatformRequest:
        return PlatformRequest(minimal=False)

    @staticmethod
    def platforms_minimal() -> PlatformRequest:
        return PlatformRequest(minimal=True)

    @staticmethod
    def customer_orders() -> CustomerOrderRequest:
        return CustomerOrderRequest(minimal=False)

    @staticmethod
    def customer_orders_minimal() -> CustomerOrderRequest:
        return CustomerOrderRequest(minimal=True)

    @staticmethod
    def order_items() -> OrderItemRequest:
        return OrderItemRequest(minimal=False)

    @staticmethod
    def order_items_minimal() -> OrderItemRequest:
        return OrderItemRequest(minimal=True)

    @staticmethod
    def payments() -> PaymentRequest:
        return PaymentRequest(minimal=False)

    @staticmethod
    def payments_minimal() -> PaymentRequest:
        return PaymentRequest(minimal=True)

    @staticmethod
    def payment_attempts() -> PaymentAttemptRequest:
        return PaymentAttemptRequest(minimal=False)

    @staticmethod
    def payment_attempts_minimal() -> PaymentAttemptRequest:
        return PaymentAttemptRequest(minimal=True)

    @staticmethod
    def shipments() -> ShipmentRequest:
        return ShipmentRequest(minimal=False)

    @staticmethod
    def shipments_minimal() -> ShipmentRequest:
        return ShipmentRequest(minimal=True)


